import { supabase } from './supabaseClient';

export interface Student {
  student_uid: string;
  name: string;
  section_id: string;
  course: string;
  branch: string;
  semester: string;
  section: string;
}

export const studentService = {
  /**
   * Fetch ALL students with face embeddings and cache them in local MMKV.
   *
   * IMPORTANT: We do NOT filter by section_id here. The face recognition
   * step happens BEFORE we know which class are in, so we must load
   * every student's embedding to find a match. Section filtering is done
   * later, on the attendance side, based on the teacher's BLE advertisement.
   *
   * Embeddings are L2-normalized on load so they are in the same unit-sphere
   * vector space as the live embeddings generated by MobileFaceNet at runtime.
   */
  async syncStudentEmbeddings(): Promise<{ count: number }> {
    console.log('[StudentService] Syncing ALL student embeddings...');
    const { data, error } = await supabase
      .from('students')
      .select('student_uid, name, face_embedding');

    if (error) {
      // Throw so FaceScanScreen can display the real error message on-screen
      console.error('[StudentService] Supabase query error:', error);
      throw new Error(
        `Supabase error ${error.code ?? ''}: ${error.message}`,
      );
    }

    if (!data || data.length === 0) {
      console.warn('[StudentService] Query succeeded but 0 rows returned.');
      throw new Error(
        'Supabase returned 0 students. Check the "students" table has data and RLS allows reads.',
      );
    }

    const embeddingMap: Record<string, any> = {};
    data.forEach((s: any) => {
      if (s.face_embedding && Array.isArray(s.face_embedding)) {
        // L2-normalize the stored embedding so cosine similarity works reliably
        const raw: number[] = s.face_embedding;
        const norm = Math.sqrt(raw.reduce((sum, v) => sum + v * v, 0));
        const normalized = norm > 0 ? raw.map(v => v / norm) : raw;
        embeddingMap[s.student_uid] = {
          name: s.name,
          embedding: normalized,
        };
      }
    });

    const { storageService } = await import('./storageService');
    storageService.setObject('studentEmbeddings', embeddingMap);

    const count = Object.keys(embeddingMap).length;
    console.log(`[StudentService] Synced ${count}/${data.length} students with face embeddings.`);

    if (count === 0) {
      throw new Error(
        `${data.length} student(s) found but NONE have a face_embedding. Register face data via the admin dashboard first.`,
      );
    }

    return { count };
  },

  /**
   * Fetch students for a specific section.
   */
  async getStudentsBySection(section_id: string): Promise<Student[]> {
    try {
      const { data, error } = await supabase
        .from('students')
        .select('*')
        .eq('section_id', section_id);

      if (error) {
        throw error;
      }

      return data as Student[];
    } catch (error: any) {
      console.warn('Using mock data for getStudentsBySection.');
      return [
        {
          student_uid: 'S101',
          name: 'Alice Johnson',
          section_id,
          course: 'B.Tech',
          branch: 'CSE',
          semester: '6',
          section: 'A',
        },
      ];
    }
  },

  /**
   * Fetch students using course, branch, semester, and section.
   */
  async getStudentsByClassDetails(
    course: string,
    branch: string,
    semester: string,
    section: string,
  ): Promise<Student[]> {
    try {
      const { data, error } = await supabase
        .from('students')
        .select('*')
        .eq('course', course)
        .eq('branch', branch)
        .eq('semester', semester)
        .eq('section', section);

      if (error) {
        throw error;
      }

      return data as Student[];
    } catch (error: any) {
      return [
        {
          student_uid: 'S101',
          name: 'Alice Johnson',
          section_id: 'SEC_A',
          course,
          branch,
          semester,
          section,
        },
      ];
    }
  },
};
